//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDaddyDns.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoDaddyDns.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontAwesome {
            get {
                object obj = ResourceManager.GetObject("FontAwesome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking your current IP address....
        /// </summary>
        internal static string frmMain_CheckingIp {
            get {
                return ResourceManager.GetString("frmMain_CheckingIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while trying to obtain the current IP address: {0}..
        /// </summary>
        internal static string frmMain_ErrorCurrentIp {
            get {
                return ResourceManager.GetString("frmMain_ErrorCurrentIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect your current IP address..
        /// </summary>
        internal static string frmMain_NoNetworkCurrentIp {
            get {
                return ResourceManager.GetString("frmMain_NoNetworkCurrentIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the IP address of {0}....
        /// </summary>
        internal static string frmMain_UpdatingDomainIp {
            get {
                return ResourceManager.GetString("frmMain_UpdatingDomainIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the IP address of your domain(s)....
        /// </summary>
        internal static string frmMain_UpdatingDomainsIp {
            get {
                return ResourceManager.GetString("frmMain_UpdatingDomainsIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current IP address is: {0}.
        /// </summary>
        internal static string frmMain_YourCurrentIp {
            get {
                return ResourceManager.GetString("frmMain_YourCurrentIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ttl must be an integer.
        /// </summary>
        internal static string frmSettings_InvalidTtl {
            get {
                return ResourceManager.GetString("frmSettings_InvalidTtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string Text_NA {
            get {
                return ResourceManager.GetString("Text_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string UpdateStatus_Error {
            get {
                return ResourceManager.GetString("UpdateStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string UpdateStatus_NA {
            get {
                return ResourceManager.GetString("UpdateStatus_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Changed.
        /// </summary>
        internal static string UpdateStatus_NotChanged {
            get {
                return ResourceManager.GetString("UpdateStatus_NotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string UpdateStatus_OK {
            get {
                return ResourceManager.GetString("UpdateStatus_OK", resourceCulture);
            }
        }
    }
}
